daily_fresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from .settings import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include(('df_user.urls', 'df_user'), namespace='df_user')),
    url(r'^', include(('df_goods.urls', 'df_goods'), namespace='df_goods')),
    url(r'^cart/', include(('df_cart.urls', 'df_cart'), namespace='df_cart')),
    url(r'^order/', include(('df_order.urls', 'df_order'), namespace='df_order')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}),
    # url(r'^search/', include('haystack.urls')),
]

df_cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^add(?P<goods_id>\d+)_(?P<count>\d+)/$", views.add, name="add"),
    url(r"^$", views.cart, name="cart"),
    url(r"^edit(?P<cart_id>\d+)_(?P<count>\d+)/$", views.edit, name="edit"),
    url(r"^delete(?P<cart_id>\d+)/$", views.delete, name="delete"),

]

df_goods/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<goods_id>\d+)/$', views.detail, name='detail'),
    url(r'^list(?P<type_id>\d+)_(?P<page_id>\d+)_(?P<sort_id>\d+)/$', views.goods_list, name='goods_list'),
    # url(r'^search/', views.ordinary_search, name="ordinary_search"),
    url(r'^search/', views.MySearchView(), name="search")
]

df_user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^register_handle/', views.register_handle, name='register_handle'),
    url(r'^register_exist/', views.register_exist, name='register_exist'),
    url(r'^login/', views.login, name='login'),
    url(r'^login_handle/', views.login_handle, name='login_handle'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^info/', views.info, name='info'),
    url(r'^order/(?P<order_page>\d+)/', views.order, name='order'),
    url(r'^site/', views.site, name='site'),
]

df_goods/models.py
from django.db import models

from tinymce.models import HTMLField

# Create your models here.
class TypeInfo(models.Model):
    ttitle = models.CharField(max_length=20, verbose_name = '分类')
    is_delete = models.BooleanField(default=False)

    def __str__(self):
        return self.ttitle

    class Meta:
        verbose_name = '商品类型'
        verbose_name_plural = verbose_name

class GoodsInfo(models.Model):
    is_delete = models.BooleanField(default=False)
    gtitle = models.CharField(max_length=20, unique=True, verbose_name='商品名称')
    gprice = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='商品价格')
    gjianjie = models.CharField(max_length=200, verbose_name='简介')
    gunit = models.CharField(max_length=20, default='500g', verbose_name='单位重量')
    gclick = models.IntegerField(default=0, null=False, verbose_name='点击量')
    gcontent = HTMLField(max_length=200, verbose_name='详情')
    gkucun = models.IntegerField(default=0, verbose_name='库存')
    gpic = models.ImageField(upload_to='df_goods/image/%Y/%m', null=True, blank=True, verbose_name='商品图片')
    gtype = models.ForeignKey(TypeInfo, verbose_name='分类', on_delete=models.CASCADE)
    class Meta():
        verbose_name = '商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.gtitle

df_goods/views.py
from django.shortcuts import render, HttpResponse
from django.core.paginator import Paginator
from datetime import datetime

from .models import TypeInfo, GoodsInfo
from df_user.models import GoodsBrowser
from df_cart.models import CartInfo

# Create your views here.
def index(request):
    typelist = TypeInfo.objects.all()
    # 按照上传顺序
    type0 = typelist[0].goodsinfo_set.order_by('-id')[0:4]
    # 按照点击量
    type01 = typelist[0].goodsinfo_set.order_by('-gclick')[0:4]
    type1 = typelist[1].goodsinfo_set.order_by('-id')[0:4]
    type11 = typelist[1].goodsinfo_set.order_by('-gclick')[0:4]
    type2 = typelist[2].goodsinfo_set.order_by('-id')[0:4]
    type21 = typelist[2].goodsinfo_set.order_by('-gclick')[0:4]
    type3 = typelist[3].goodsinfo_set.order_by('-id')[0:4]
    type31 = typelist[3].goodsinfo_set.order_by('-gclick')[0:4]
    type4 = typelist[4].goodsinfo_set.order_by('-id')[0:4]
    type41 = typelist[4].goodsinfo_set.order_by('-gclick')[0:4]
    type5 = typelist[5].goodsinfo_set.order_by('-id')[0:4]
    type51 = typelist[5].goodsinfo_set.order_by('-gclick')[0:4]

    context = {
        'title': '主页',
        'guest_cart': 1,
        'cart_num': cart_count(request),
        'type0': type0, 'type01': type01,
        'type1': type1, 'type11': type11,
        'type2': type2, 'type21': type21,
        'type3': type3, 'type31': type31,
        'type4': type4, 'type41': type41,
        'type5': type5, 'type51': type51,
    }
    return render(request, 'df_goods/index.html', context=context)

def detail(request, goods_id):
    goods = GoodsInfo.objects.filter(id=int(goods_id)).first()
    # 点击量+1
    goods.gclick = goods.gclick + 1
    goods.save()

    # 上新
    news = goods.gtype.goodsinfo_set.order_by('-id')[0:2]
    context = {
        'title': '商品详情',
        'guest_cart': 1,
        'cart_num': cart_count(request),
        'goods': goods,
        'id': goods_id,
        'news': news,
    }
    resposne = render(request, 'df_goods/detail.html', context=context)

    # 更新用户浏览记录，保持在5条
    if 'user_id' in request.session:
        user_id = request.session.get('user_id')
        try:
            browsed_good = GoodsBrowser.objects.get(user_id=int(user_id), good_id=int(goods_id))
        except:
            browsed_good = None
        if browsed_good:
            browsed_good.browser_time = datetime.now()
            browsed_good.save()
        else:
            GoodsBrowser.objects.create(user_id=int(user_id), good_id=int(goods_id))
            browsed_goods = GoodsBrowser.objects.filter(user_id=int(user_id))
            if browsed_goods.count() > 5:
                ordered_goods = browsed_goods.order_by('-browser_time')
                for _ in ordered_goods[5:]:
                    _.delete()

    return resposne

def goods_list(request, type_id, page_id, sort_id):
    typeinfo = TypeInfo.objects.get(id=int(type_id))
    # 上新
    news = typeinfo.goodsinfo_set.order_by('-id')[0:2]
    cart_num, guest_cart = 0, 0
    goods_list =[]

    user_id = request.session.get('user_id')
    if user_id:
        guest_cart = 1

    # 默认最新
    if sort_id == '1':
        goods_list = typeinfo.goodsinfo_set.order_by('-id')
    # 按照价格
    if sort_id == '2':
        goods_list = typeinfo.goodsinfo_set.order_by('-gprice')
    # 按照人气
    if sort_id == '3':
        goods_list = typeinfo.goodsinfo_set.order_by('-gprice')

    # 分页
    paginator = Paginator(goods_list, 4)
    # 返回page对象，包含商品信息
    page = paginator.page(int(page_id))
    context = {
        'title': '商品列表',
        'cart_num': cart_count(request),
        'guest_cart': guest_cart,
        'news': news,
        'sort_id': sort_id,
        'typeinfo': typeinfo,
        'page': page,
        'paginator': paginator,
    }
    return render(request, 'df_goods/list.html', context=context)

def cart_count(request):
    if 'user_id' in request.session:
        user_id = int(request.session.get('user_id'))
        return CartInfo.objects.filter(user_id=user_id).count()
    return cart_count

def ordinary_search(request):

    from django.db.models import Q

    search_keywords = request.GET.get('q', '')
    pindex = request.GET.get('pindex', 1)
    search_status = 1
    cart_num, guest_cart = 0, 0

    try:
        user_id = request.session['user_id']
    except:
        user_id = None

    if user_id:
        guest_cart = 1
        cart_num = CartInfo.objects.filter(user_id=int(user_id)).count()

    goods_list = GoodsInfo.objects.filter(
        Q(gtitle__icontains=search_keywords) |
        Q(gcontent__icontains=search_keywords) |
        Q(gjianjie__icontains=search_keywords)).order_by("gclick")

    if goods_list.count() == 0:
        # 商品搜索结果为空，返回推荐商品
        search_status = 0
        goods_list = GoodsInfo.objects.all().order_by("gclick")[:4]

    paginator = Paginator(goods_list, 4)
    page = paginator.page(int(pindex))

    context = {
        'title': '搜索列表',
        'search_status': search_status,
        'guest_cart': guest_cart,
        'cart_num': cart_num,
        'page': page,
        'paginator': paginator,
    }
    return render(request, 'df_goods/ordinary_search.html', context)

from haystack.views import SearchView
class MySearchView(SearchView):
    def extra_context(self):
        context = super(MySearchView, self).extra_context()
        context['title'] = '搜索'
        context['guest_cart'] = 1
        context['cart_num'] = cart_count(self.request)
        # print(context['cart_count'])
        return context

templates/df_goods/base.html
{% extends "base.html" %}
{% load static %}

{% block center_body %}
<div class="navbar_con">
    <div class="navbar clearfix">
        <div class="subnav_con fl">
            <h1>全部商品分类</h1>
            <span></span>
            <ul class="subnav">
                <li><a href="/list2_1_1" class="fruit">新鲜水果</a></li>
                <li><a href="/list1_1_1" class="seafood">海鲜水产</a></li>
                <li><a href="/list3_1_1" class="meet">猪牛羊肉</a></li>
                <li><a href="/list4_1_1" class="egg">禽类蛋品</a></li>
                <li><a href="/list5_1_1" class="vegetables">新鲜蔬菜</a></li>
                <li><a href="/list6_1_1" class="ice">速冻食品</a></li>
            </ul>
        </div>
        <ul class="navlist fl">
            <li><a href="{% url 'df_goods:index' %}">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">手机生鲜</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>
</div>
<div class="breadcrumb">
    全部分类 > {{ title }}
    {% if id|default:' ' != ' ' %}
    > 商品详情
    {% endif %}
</div>

{% block center_content %}
{% endblock center_content %}

{% endblock center_body %}

templates/df_goods/detail.html
{% extends 'df_goods/base.html' %}
{% block head %}
<script type="text/javascript">
	function plus() {
		num = parseInt($('.num_show').val());
		kucun = parseInt($('.goods_kucun').html());
		if (num < kucun) {
			$('.num_show').val(num + 1);
			$('.num_show').blur();
		}
	};

	function minus() {
		num = parseInt($('.num_show').val());
		if (num > 1) {
			$('.num_show').val(num - 1);
			$('.num_show').blur();
		}
	}
	$(function () {
		$('.num_show').blur(function () {
			num = parseInt($('.num_show').val());
			if (num <= 1) {
				num = 1;
			}
			kucun = parseInt($('.goods_kucun').html());
			if (num >= kucun) {
				num = kucun;
			}
			price = parseFloat($('#gprice').html());
			total = num * price;
			$('.num_show').val(num);
			$('#gtotal').html(total.toFixed(2) + '元');

		});
	})
</script>
{% endblock head %}

{% load static %}
{% block center_content %}

<div class="goods_detail_con clearfix">
	<div class="goods_detail_pic fl"><img src="/media/{{ goods.gpic }}"></div>

	<div class="goods_detail_list fr">
		<h3>{{ goods.gtitle }}</h3>
		<p>{{ goods.gjianjie }}</p>
		<div class="prize_bar">
			<span class="show_pirze">¥<em id="gprice">{{ goods.gprice }}</em></span>
			<span class="show_unit">单 位：500g</span>
			<span class="show_unit">库 存：<span class="goods_kucun">{{ goods.gkucun }}</span></span>
		</div>
		<div class="goods_num clearfix">
			<div class="num_name fl">数 量：</div>
			<div class="num_add fl">
				<input type="text" class="num_show fl" value="1">
				<a href="javascript:plus();" class="add fr">+</a>
				<a href="javascript:minus();" class="minus fr">-</a>
			</div>
		</div>
		<div class="total">总价：<em id="gtotal">{{ goods.gprice }}</em></div>
		<div class="operate_btn">
			{% if request.session.user_id|default:'' != '' %}
			<a href="javascript:;" class="buy_btn">立即购买</a>
			{% else %}
			<a href="{% url 'df_user:login' %}" class="buy_btn" id="buy_now">立即购买</a>

			{% endif %}
			{% if request.session.user_id|default:'' != ''  %}
			<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>
			{% else %}

			<a href="{% url 'df_user:login' %}" class="add_cart" id="add_cart">加入购物车</a>
			{% endif %}
		</div>
	</div>
</div>

<div class="main_wrap clearfix">
	<div class="l_wrap fl clearfix">
		<div class="new_goods">
			<h3>新品推荐</h3>
			<ul>
				{% for g in news %}
				<li>
					<a href="/{{ g.id }}"><img src="/media/{{ g.gpic }}"></a>
					<h4><a href="/{{ g.id }}">{{ g.gtitle }}</a></h4>
					<div class="prize">{{ g.gprice }}</div>
				</li>
				{% endfor %}


			</ul>
		</div>
	</div>

	<div class="r_wrap fr clearfix">
		<ul class="detail_tab clearfix">
			<li class="active">商品介绍</li>
			<li>评论</li>
		</ul>

		<div class="tab_content">
			<dl>
				<dt>商品详情：</dt>
				<dd>{{ goods.gcontent|safe }}
				</dd>
			</dl>
		</div>

	</div>
</div>


<div class="add_jump"></div>

<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script type="text/javascript">
	$(document).ready(function () {

		$(".buy_btn").click(function () {
			if ($('.login_btn').text().indexOf('登录') >= 0) {
				alert('请登陆后购买');
				location.href("{% url 'df_user:login' %}");
				return;
			}
			num = parseInt($('.num_show').val());
			$.get('/cart/add{{ goods.id }}_' + num + '/', function (data) {
				$('#show_count').text(data.count);
			});
			location.href = "{% url 'df_cart:cart' %}";

		});

		$('#add_cart').click(function () {

			var $add_x = $('#add_cart').offset().top;
			var $add_y = $('#add_cart').offset().left;

			var $to_x = $('#show_count').offset().top;
			var $to_y = $('#show_count').offset().left;

			$(".add_jump").css({
				'left': $add_y + 80,
				'top': $add_x + 10,
				'display': 'block'
			});

				if ($('.login_btn').text().indexOf('登录') >= 0) {
					alert('请登陆后购买');
					location.href("{% url 'df_user:login' %}");
					return;
				}

				$(".add_jump").stop().animate({
						'left': $to_y + 7,
						'top': $to_x + 7
					},
					"fast",
					function () {
						$(".add_jump").fadeOut('fast', function () {
							count = $('.num_show').val();
							<!-- $('#show_count').html(count); -->
						});
					});

				num = parseInt($('.num_show').val());
				$.get('/cart/add{{ goods.id }}_' + num + '/', function (data) {
					$('#show_count').text(data.count);
				});

		});
	});
</script>
{% endblock center_content %}

templates/df_goods/index.html
{% extends "df_goods/base.html" %}
{% load static %}
{% block head %}
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock head %}
{% block center_body %}


<div class="navbar_con">
	<div class="navbar">
		<h1 class="fl">全部商品分类</h1>
		<ul class="navlist fl">
			<li><a href="{% url 'df_goods:index' %}">首页</a></li>
			<li class="interval">|</li>
			<li><a href="">手机生鲜</a></li>
			<li class="interval">|</li>
			<li><a href="">抽奖</a></li>
		</ul>
	</div>
</div>

<div class="center_con clearfix">
	<ul class="subnav fl">
		<li><a href="/list2_1_1" class="fruit">新鲜水果</a></li>
		<li><a href="/list1_1_1" class="seafood">海鲜水产</a></li>
		<li><a href="/list3_1_1" class="meet">猪牛羊肉</a></li>
		<li><a href="/list4_1_1" class="egg">禽类蛋品</a></li>
		<li><a href="/list5_1_1" class="vegetables">新鲜蔬菜</a></li>
		<li><a href="/list6_1_1" class="ice">速冻食品</a></li>
	</ul>
	<div class="slide fl">
		<ul class="slide_pics">
			<li><img src="{% static 'images/slide.jpg' %}" alt="幻灯片"></li>
			<li><img src="{% static 'images/slide02.jpg' %}" alt="幻灯片"></li>
			<li><img src="{% static 'images/slide03.jpg' %}" alt="幻灯片"></li>
			<li><img src="{% static 'images/slide04.jpg' %}" alt="幻灯片"></li>
		</ul>
		<div class="prev"></div>
		<div class="next"></div>
		<ul class="points"></ul>
	</div>
	<div class="adv fl">
		<a href="#"><img src="{% static 'images/adv01.jpg' %}"></a>
		<a href="#"><img src="{% static 'images/adv01.jpg' %}"></a>
	</div>
</div>


<div class="list_model">
	<div class="list_title clearfix">
		<h3 class="fl" id="model01">新鲜水果</h3>
		<div class="subtitle fl">
			<span>|</span>
			{% for g in  type11 %}
			<a href="/{{ g.id }}/">{{ g.gtitle|slice:'10'}}</a>
			{% endfor %}
		</div>
		<a href="/list2_1_1/" class="goods_more fr" id="fruit_more">查看更多 ></a>
	</div>

	<div class="goods_con clearfix">
		<div class="goods_banner fl"><img src="{% static 'images/banner01.jpg' %}"></div>
		<ul class="goods_list fl">
			{% for g in type1 %}
			<li>
				<h4><a href="/{{ g.id }}/">{{ g.gtitle }}</a></h4>
				<a href="/{{ g.id }}/"><img src="/media/{{ g.gpic }}"></a>
				<div class="prize"> ￥ {{ g.gprice }}</div>
			</li>
			{% endfor %}
			</li>
		</ul>
	</div>
</div>

<div class="list_model">
	<div class="list_title clearfix">
		<h3 class="fl" id="model02">海鲜水产</h3>
		<div class="subtitle fl">
			<span>|</span>
			{% for g in  type01 %}
			<a href="/{{ g.id }}/">{{ g.gtitle|slice:'10'}}</a>
			{% endfor %}
		</div>
		<a href="/list1_1_1/" class="goods_more fr" id="fruit_more">查看更多 ></a>
	</div>

	<div class="goods_con clearfix">
		<div class="goods_banner fl"><img src="{% static 'images/banner02.jpg' %}"></div>
		<ul class="goods_list fl">
			{% for g in type0 %}
			<li>
				<h4><a href="/{{ g.id }}/">{{ g.gtitle }}</a></h4>
				<a href="/{{ g.id }}/"><img src="/media/{{ g.gpic }}"></a>
				<div class="prize"> ￥ {{ g.gprice }}</div>
			</li>
			{% endfor %}
			</li>
		</ul>
	</div>
</div>

<div class="list_model">
	<div class="list_title clearfix">
		<h3 class="fl" id="model03">猪牛羊肉</h3>
		<div class="subtitle fl">
			<span>|</span>
			{% for g in  type21 %}
			<a href="/{{ g.id }}/">{{ g.gtitle|slice:'10'}}</a>
			{% endfor %}
		</div>
		<a href="/list3_1_1/" class="goods_more fr" id="fruit_more">查看更多 ></a>
	</div>

	<div class="goods_con clearfix">
		<div class="goods_banner fl"><img src="{% static 'images/banner03.jpg' %}"></div>
		<ul class="goods_list fl">
			{% for g in type2 %}
			<li>
				<h4><a href="/{{ g.id }}/">{{ g.gtitle }}</a></h4>
				<a href="/{{ g.id }}/"><img src="/media/{{ g.gpic }}"></a>
				<div class="prize"> ￥ {{ g.gprice }}</div>
			</li>
			{% endfor %}
			</li>
		</ul>
	</div>
</div>

<div class="list_model">
	<div class="list_title clearfix">
		<h3 class="fl" id="model04">禽类蛋品</h3>
		<div class="subtitle fl">
			<span>|</span>
			{% for g in  type31 %}
			<a href="/{{ g.id }}/">{{ g.gtitle|slice:'10'}}</a>
			{% endfor %}
		</div>
		<a href="/list4_1_1/" class="goods_more fr" id="fruit_more">查看更多 ></a>
	</div>

	<div class="goods_con clearfix">
		<div class="goods_banner fl"><img src="{% static 'images/banner04.jpg' %}"></div>
		<ul class="goods_list fl">
			{% for g in type3 %}
			<li>
				<h4><a href="/{{ g.id }}/">{{ g.gtitle }}</a></h4>
				<a href="/{{ g.id }}/"><img src="/media/{{ g.gpic }}"></a>
				<div class="prize"> ￥ {{ g.gprice }}</div>
			</li>
			{% endfor %}
			</li>
		</ul>
	</div>
</div>

<div class="list_model">
	<div class="list_title clearfix">
		<h3 class="fl" id="model05">新鲜蔬菜</h3>
		<div class="subtitle fl">
			<span>|</span>
			{% for g in  type41 %}
			<a href="/{{ g.id }}/">{{ g.gtitle|slice:'10'}}</a>
			{% endfor %}
		</div>
		<a href="/list5_1_1/" class="goods_more fr" id="fruit_more">查看更多 ></a>
	</div>

	<div class="goods_con clearfix">
		<div class="goods_banner fl"><img src="{% static 'images/banner05.jpg' %}"></div>
		<ul class="goods_list fl">
			{% for g in type4 %}
			<li>
				<h4><a href="/{{ g.id }}/">{{ g.gtitle }}</a></h4>
				<a href="/{{ g.id }}/"><img src="/media/{{ g.gpic }}"></a>
				<div class="prize"> ￥ {{ g.gprice }}</div>
			</li>
			{% endfor %}
			</li>
		</ul>
	</div>
</div>

<div class="list_model">
	<div class="list_title clearfix">
		<h3 class="fl" id="model06">速冻食品</h3>
		<div class="subtitle fl">
			<span>|</span>
			{% for g in  type51 %}
			<a href="/{{ g.id }}/">{{ g.gtitle|slice:'10'}}</a>
			{% endfor %}
		</div>
		<a href="/list6_1_1/" class="goods_more fr" id="fruit_more">查看更多 ></a>
	</div>

	<div class="goods_con clearfix">
		<div class="goods_banner fl"><img src="{% static 'images/banner06.jpg' %}"></div>
		<ul class="goods_list fl">
			{% for g in type5 %}
			<li>
				<h4><a href="/{{ g.id }}/">{{ g.gtitle }}</a></h4>
				<a href="/{{ g.id }}/"><img src="/media/{{ g.gpic }}"></a>
				<div class="prize"> ￥ {{ g.gprice }}</div>
			</li>
			{% endfor %}
			</li>
		</ul>
	</div>
</div>

<script type="text/javascript" src="js/slide.js"></script>
<script type="text/javascript">
	BCSlideshow('focuspic');
	var oFruit = document.getElementById('fruit_more');
	var oShownum = document.getElementById('show_count');

	var hasorder = localStorage.getItem('order_finish');

	if (hasorder) {
		oShownum.innerHTML = '2';
	}

	oFruit.onclick = function () {
		window.location.href = 'list.html';
	}
</script>


{% endblock center_body %}

templates/df_goods/list.html
{% extends "df_goods/base.html" %}
{% block center_content %}

<div class="main_wrap clearfix">
	<div class="l_wrap fl clearfix">
		<div class="new_goods">
			<h3>新品推荐</h3>
			<ul>
				{% for g in news %}
				<li>
					<a href="/{{ g.id }}"><img src="/media/{{ g.gpic }}"></a>
					<h4><a href="/{{ g.id }}">{{ g.gtitle }}</a></h4>
					<div class="prize">{{ g.gprice }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>

	<div class="r_wrap fr clearfix">
		<div class="sort_bar">
			<a href="/list{{ typeinfo.id }}_1_1" {% if sort_id == '1' %} class="active" {% endif %}>默认</a>
			<a href="/list{{ typeinfo.id }}_1_2" {% if sort_id == '2' %} class="active" {% endif %}>价格</a>
			<a href="/list{{ typeinfo.id }}_1_3" {% if sort_id == '3' %} class="active" {% endif %}>人气</a>
		</div>

		<ul class="goods_type_list clearfix">

			{% for g in page %}
			<li>
				<a href="/{{ g.id }}/"><img src="/media/{{ g.gpic }}"></a>
				<h4><a href="/{{ g.id }}/">{{ g.gtitle }}</a></h4>
				<div class="operate">
					<span class="prize">￥{{ g.gprice }}</span>
					<span class="unit">{{ g.gunit }}</span>
					<a href="{% url 'df_cart:add' g.id 1 %}" class="add_goods" title="加入购物车"></a>
				</div>
			</li>
			{% endfor %}
		</ul>

		<div class="pagenation">
			{% if page.has_previous %}
			<a href="/list{{ typeinfo.id }}_{{ page.previous_page_number }}_{{ sort_id }}">上一页</a>
			{% endif %}
			{% for pindex in paginator.page_range %} {% if pindex == page.number %}
			<a href="/list{{ typeinfo.id }}_{{ pindex }}_{{ sort_id }}" class="active">{{ pindex }}
			</a>
			{% else %}
			<a href="/list{{ typeinfo.id }}_{{ pindex }}_{{ sort_id }}">{{ pindex }}</a>
			{% endif %}
			{% endfor %}
			{% if page.has_next %}
			<a href="/list{{ typeinfo.id }}_{{ page.next_page_number }}_{{ sort_id }}">下一页</a>
			{% endif %}
		</div>
	</div>
</div>
{% endblock center_content %}