daily_fresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from .settings import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include(('df_user.urls', 'df_user'), namespace='df_user')),
    url(r'^', include(('df_goods.urls', 'df_goods'), namespace='df_goods')),
    url(r'^cart/', include(('df_cart.urls', 'df_cart'), namespace='df_cart')),
    url(r'^order/', include(('df_order.urls', 'df_order'), namespace='df_order')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}),
    # url(r'^search/', include('haystack.urls')),
]

df_cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^add(?P<goods_id>\d+)_(?P<count>\d+)/$", views.add, name="add"),
    url(r"^$", views.cart, name="cart"),
    url(r"^edit(?P<cart_id>\d+)_(?P<count>\d+)/$", views.edit, name="edit"),
    url(r"^delete(?P<cart_id>\d+)/$", views.delete, name="delete"),

]

df_user/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^register_handle/', views.register_handle, name='register_handle'),
    url(r'^register_exist/', views.register_exist, name='register_exist'),
    url(r'^login/', views.login, name='login'),
    url(r'^login_handle/', views.login_handle, name='login_handle'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^info/', views.info, name='info'),
    url(r'^order/(?P<order_page>\d+)/', views.order, name='order'),
    url(r'^site/', views.site, name='site'),
]

df_order/models.py
from django.db import models

# Create your models here.
class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True, verbose_name='大订单号')
    user = models.ForeignKey("df_user.UserInfo", verbose_name='订单用户', on_delete=models.CASCADE)
    odate = models.DateTimeField(auto_now=True, verbose_name='订单创建时间')
    ototal = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='订单总价')
    oaddress = models.CharField(max_length=150, verbose_name='订单地址')
    ois_pay = models.BooleanField(default=False, verbose_name='是否支付')

    class Meta:
        verbose_name = '订单'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{user}在{date}订单'.format(user=self.user.uname, date=self.odate)

class OrderDetailInfo(models.Model):
    goods = models.ForeignKey("df_goods.GoodsInfo", verbose_name='商品', on_delete=models.CASCADE)
    order = models.ForeignKey("OrderInfo", verbose_name='订单', on_delete=models.CASCADE)
    count = models.IntegerField(verbose_name='商品数量')
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='商品价格')

    class Meta:
        verbose_name = '订单详情'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{goods}(数量为{count})'.format(goods=self.goods.gtitle, count=self.count)

df_user/models.py
from django.db import models
from df_goods.models import GoodsInfo
from datetime import datetime
# Create your models here.
class UserInfo(models.Model):
    uname = models.CharField(max_length=20, unique=True)
    upwd = models.CharField(max_length=40, blank=False)
    uemail = models.EmailField(unique=True)
    uaddress = models.CharField(max_length=100, default='')
    uphone = models.CharField(max_length=11, default='')
    uyoubian = models.CharField(max_length=6, default='')
    ushou = models.CharField(max_length=20, default='')

    def _str__(self):
        return self.uname

class GoodsBrowser(models.Model):
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE, verbose_name='用户ID')
    good = models.ForeignKey(GoodsInfo, on_delete=models.CASCADE, verbose_name='商品ID')
    browser_time = models.DateTimeField(default=datetime.now, verbose_name='浏览时间')

    class Meta:
        verbose_name = '用户浏览记录'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{user}浏览记录{title}'.format(user=self.user.uname, title=self.good.gtitle)

df_user/views.py
from django.shortcuts import render, redirect, HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from django.urls import reverse
from django.core.paginator import Paginator
import hashlib

from . import user_decorator
from df_order.models import OrderInfo, OrderDetailInfo
from .models import UserInfo, GoodsBrowser


# Create your views here.
def register(request):
    # 注册视图
    context = {
        'title':'注册',
    }
    return render(request, 'df_user/register.html', context=context)

def register_handle(request):
    # 处理注册信息
    # 获取注册信息
    post = request.POST
    user_name = post.get('user_name')
    pwd = post.get('pwd')
    cpwd = post.get('cpwd')
    uemail = post.get('email')

    # 两次输入的密码不一致回到注册页面
    if pwd != cpwd:
        return redirect('df_user:register')
    # 对密码进行sha1加密
    sha1 = hashlib.sha1()
    sha1.update(pwd.encode('utf-8'))
    encrypted_pwd = sha1.hexdigest()

    # 创建对象
    UserInfo.objects.create(
        uname = user_name,
        upwd = encrypted_pwd,
        uemail = uemail,
    )

    context = {
        'title':'用户登录',
        'user_name':user_name,
    }
    # 转到登录页面
    return render(request, 'df_user/login.html', context=context)

def register_exist(request):
    # 判断数据库中是否已存在该用户名
    user_name = request.GET.get('user_name')
    count = UserInfo.objects.filter(uname=user_name).count()
    return JsonResponse({'count':count})

def login(request):
    user_name = request.COOKIES.get('user_name', '')
    context = {
        'title':'用户登录',
        'user_name': user_name,
        'error_name': 0,
        'error_pwd':0,
    }
    return render(request, 'df_user/login.html', context=context)

def login_handle(request):
    # 获取登录信息
    post = request.POST
    user_name = post.get('user_name','')
    pwd = post.get('pwd')
    jizhu = post.get('jizhu', 0)
    # print(user_name, pwd, jizhu)
    # 从数据库获取用户信息
    users = UserInfo.objects.filter(uname=user_name)
    # 判断用户名是否正确
    if len(users) == 1:
        # 加密密码
        sha1 = hashlib.sha1()
        sha1.update(pwd.encode('utf-8'))
        encrypted_pwd = sha1.hexdigest()
        # 判断密码是否相同
        if encrypted_pwd == users[0].upwd:
            url = request.COOKIES.get('url', '/')
            # 跳转到登录之前的链接或者首页
            red = HttpResponseRedirect(url)
            # 判断是否要记住用户名
            if jizhu:
                red.set_cookie('user_name', user_name)
            else:
                red.set_cookie('user_name', '', max_age=-1)
            request.session['user_id'] = users[0].id
            request.session['user_name'] = user_name
            return red

        # 密码错误
        else:
            context = {
            'title':'用户登录',
            'user_name':user_name,
            'pwd':pwd,
            'error_name':0,
            'error_pwd':1,
            }
            return render(request, 'df_user/login.html', context=context)

    # 用户名错误
    else:
        context = {
        'title':'用户登录',
        'user_name':user_name,
        'pwd':pwd,
        'error_name':1,
        'error_pwd':0,
        }
        return render(request, 'df_user/login.html', context=context)

def logout(request):
    request.session.flush()
    return redirect('df_user:login')

@user_decorator.login
def info(request):
    # 获取对象
    user_id = request.session.get('user_id')
    user = UserInfo.objects.filter(id=user_id).first()
    # print(user.uname)
    goods_list = []
    browser_goods = GoodsBrowser.objects.filter(user_id=int(user_id)).order_by('-browser_time')
    if browser_goods:
        goods_list = [ browser_good.good for browser_good in browser_goods]
        explain = '最近浏览'
    else:
        explain = '无最近浏览'
    context = {
        'title':'用户中心',
        'page_name':1,
        'user_name': user.uname,
        'user_address': user.uaddress,
        'user_phone': user.uphone,
        'goods_list': goods_list,
        'explain': explain,
    }
    return render(request, 'df_user/user_center_info.html', context=context)

@user_decorator.login
def order(request, order_page):
    user_id = request.session.get('user_id')
    order_list = OrderInfo.objects.filter(user_id=int(user_id)).order_by('-odate')
    paginator = Paginator(order_list, 2)
    page = paginator.page(int(order_page))
    context = {
        'title': '用户中心',
        'page_name': 1,
        'paginator': paginator,
        'page': page,
    }
    return render(request, 'df_user/user_center_order.html', context=context)

@user_decorator.login
def site(request):
    user_id = request.session.get('user_id')
    user = UserInfo.objects.filter(id=user_id).first()
    if request.method == 'POST':
        post = request.POST
        user.ushou = post.get('ushou')
        user.uaddress = post.get('uaddress')
        user.uyoubian = post.get('uyoubian')
        user.uphone = post.get('uphone')
        user.save()

    context = {
        'title':'用户中心',
        'page_name':1,
        'user': user,
    }
    return render(request, 'df_user/user_center_site.html', context=context)

templates/df_user/login.html
{% extends "base_foot.html" %}
{% load static %}
{% block head %}
<script>
$(function(){
	if({{ error_name }} == 1){
		$(".user_error").html('用户名错误').show();
	};
	if({{ error_pwd }} == 1){
		$(".pwd_error").html('密码错误').show();
	};
	$(".name_input").blur(function(){
		var len = $(".name_input").val().length;
		if (len == 0){
			$(".user_error").html('用户名不能为空').show();
		}else{
			$(".user_error").hide()
		}
	})
	$(".pass_input").blur(function(){
		var len = $(".pass_input").val().length;
		if (len == 0){
			$(".pwd_error").html('密码不能为空').show();
		}else{
			$(".pwd_error").hide()
		}
	})
})
</script>
{% endblock head %}
{% block body %}

<div class="login_top clearfix">
	<a href="index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
</div>

<div class="login_form_bg">
	<div class="login_form_wrap clearfix">
		<div class="login_banner fl"></div>
		<div class="slogan fl">日夜兼程 · 急速送达</div>
		<div class="login_form fr">
			<div class="login_title clearfix">
				<h1>用户登录</h1>
				<a href="{% url 'df_user:register' %}">立即注册</a>
			</div>
			<div class="form_input">
				<form id="login_form" action="{% url 'df_user:login_handle' %}" method="POST">
					{% csrf_token %}
					<input type="text" name="user_name" class="name_input" placeholder="请输入用户名" value="{{ user_name }}">
					<div class="user_error">输入错误</div>
					<input type="password" name="pwd" class="pass_input" placeholder="请输入密码" value="{{ pwd }}">
					<div class="pwd_error">输入错误</div>
					<div class="more_input clearfix">
						<input type="checkbox" name="jizhu" value="1" , checked="checked">
						<label>记住用户名</label>
						<a href="#">忘记密码</a>
					</div>
					<input type="submit" name="" value="登录" class="input_submit">
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock body %}

templates/df_user/register.html
{% extends "base_foot.html" %}
{% load static %}
{% block head %}


<script type="text/javascript" src="{% static 'js/regist.js' %}"></script>

{% endblock head %}
{% block body %}


<div class="register_con">
	<div class="l_con fl">
		<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
		<div class="reg_slogan">足不出户 · 新鲜每一天</div>
		<div class="reg_banner"></div>
	</div>

	<div class="r_con fr">
		<div class="reg_title clearfix">
			<h1>用户注册</h1>
			<a href="{% url 'df_user:login' %}">登录</a>
		</div>
		<div class="reg_form clearfix">
			<form id="reg_from" action="{% url 'df_user:register_handle' %}" method="POST">
				{% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>
			</form>
		</div>

	</div>

</div>
{% endblock body %}

templates/df_user/user_center_info.html
{% extends "base.html" %}
{% block center_body %}

<div class="main_con clearfix">
	<div class="left_menu_con clearfix">
		<h3>用户中心</h3>
		<ul>
			<li><a href="{% url 'df_user:info' %}" class="active">· 个人信息</a></li>
			<li><a href="{% url 'df_user:order' '1' %}">· 全部订单</a></li>
			<li><a href="{% url 'df_user:site' %}">· 收货地址</a></li>
		</ul>
	</div>
	<div class="right_content clearfix">
		<div class="info_con clearfix">
			<h3 class="common_title2">基本信息</h3>
			<ul class="user_info_list">
				<li><span>用户名：</span>{{ user_name|default:'  ' }}</li>
				<li><span>联系方式：</span>{{ user_phone|default:'&nbsp;&nbsp;' }}</li>
				<li><span>联系地址：</span>{{ user_address|default:'&nbsp;&nbsp;' }}</li>
			</ul>
		</div>

		<h3 class="common_title2">{{ explain }}</h3>

		<div class="has_view_list">
			<ul class="goods_type_list clearfix">
				{% for good in goods_list %}

				<li>
					<a href="detail.html"><img src="/media/{{ good.gpic }}"></a>
					<h4><a href="/{{good.id}}/">{{ good.gtitle }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ good.gprice }}</span>
						<span class="unit">{{ good.gprice }}/{{ good.gunit }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
</div>

{% endblock center_body %}

templates/df_user/user_center_order.html
{% extends "base.html" %}

{% block center_body %}


<div class="main_con clearfix">
	<div class="left_menu_con clearfix">
		<h3>用户中心</h3>
		<ul>
			<li><a href="{% url 'df_user:info' %}" class="active">· 个人信息</a></li>
			<li><a href="{% url 'df_user:order' '1' %}">· 全部订单</a></li>
			<li><a href="{% url 'df_user:site' %}">· 收货地址</a></li>
		</ul>
	</div>
	<div class="right_content clearfix">
		<h3 class="common_title2">全部订单</h3>

		{% for order in page %}

		<ul class="order_list_th w978 clearfix">
			<li class="col01">{{ order.odate }}</li>
			<li class="col02">订单号：{{ order.oid }}</li>
			{% if order.ois_pay %}
			<li class="col02 stress">已支付</li>
			{% else %}
			<li class="col02 stress">未支付</li>
			{% endif %}

		</ul>

		<table class="order_list_table w980">
			<tbody>
				<tr>
					<td width="55%">
						{% for detail in order.orderdetailinfo_set.all %}
						<ul class="order_goods_list clearfix">
							<li class="col01"><img src="/media/{{detail.goods.gpic}}"></li>
							<li class="col02">
								{{ detail.goods.gtitle }}<em class="good_price">{{ detail.goods.gprice }}</em>元/<em>{{ detail.goods.gunit }}g</em>
							</li>
							<li class="col03">{{ detail.count }}</li>
							<li class="col04">100元</li>
						</ul>
						{% endfor %}
					<td width="15%">{{ order.ototal }}元</td>
					{% if order.ois_pay %}
					<td width="15%">已付款</td>
					<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
					{% else %}
					<td width="15%">待付款</td>
					<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
					{% endif %}
				</tr>
			</tbody>
		</table>

		{% endfor %}

		<div class="pagenation">
			{% if page.has_previous %}
			<a href="{% url 'df_user:order' page.previous_page_number %}">上一页</a>
			{% endif %}

			{% for p in paginator.page_range %}
			{% if p == page.number %}
			<a href="{% url 'df_user:order' p %}" class="active">{{ p }}</a>
			{% else %}
			<a href="{% url 'df_user:order' p %}">{{ p }}</a>
			{% endif %}
			{% endfor %}

			{% if page.has_next %}
			<a href="{% url 'df_user:order' page.next_page_number %}">下一页</a>
			{% endif %}
		</div>
	</div>
</div>
<script>
$(function(){
	$('.col04').each(function(){
		count = $(this).prev().text();
		price = $(this).prev().prev().find('.good_price').text();
		total = parseFloat(count)*parseFloat(price)
		$(this).text(total + '元')
	})
})
</script>


{% endblock center_body %}

templates/df_user/user_center_site.html
{% extends "base.html" %}
{% block center_body %}

<div class="main_con clearfix">
	<div class="left_menu_con clearfix">
		<h3>用户中心</h3>
		<ul>
			<li><a href="{% url 'df_user:info' %}" class="active">· 个人信息</a></li>
			<li><a href="{% url 'df_user:order' '1' %}">· 全部订单</a></li>
			<li><a href="{% url 'df_user:site' %}">· 收货地址</a></li>
		</ul>
	</div>
	<div class="right_content clearfix">
		<h3 class="common_title2">收货地址</h3>
		<div class="site_con">
			<dl>
				<dt>收件人：{{ user.ushou }}</dt>
				<dt>电话：{{ user.uphone }}</dt>
				<dt>当前地址：{{ user.uaddress }}</dt>
			</dl>
		</div>
		<h3 class="common_title2">编辑地址</h3>
		<div class="site_con">
			<form action="{% url 'df_user:site' %}" method="POST">
				{% csrf_token %}
				<div class="form_group">
					<label>收件人：</label>
					<input type="text" name="ushou" value="{{ user.ushou }}">
				</div>
				<div class="form_group form_group2">
					<label>详细地址：</label>
					<textarea class="site_area" name="uaddress" >{{ user.uaddress }}</textarea>
				</div>
				<div class="form_group">
					<label>邮编：</label>
					<input type="text" name="uyoubian" value="{{ user.uyoubian }}">
				</div>
				<div class="form_group">
					<label>手机：</label>
					<input type="text" name="uphone" value="{{ user.uphone }}">
				</div>

				<input type="submit" name="" value="提交" class="info_submit">
			</form>
		</div>
	</div>
</div>



{% endblock center_body %}